apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project1
  namespace: argocd
spec:
  destinations:
    # allowed cluster+namespace destinations
    - name: in-cluster
      namespace: namespace3
      server: https://kubernetes.default.svc
  sourceNamespaces:
    # allowed deployment namespaces
    - namespace3